name: Blender Addon Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-addon:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        blender_version: ["4.2.0", "4.3.0"]  # Add newer versions as needed!

    env:
      BLENDER_VERSION: ${{ matrix.blender_version }}
      BLENDER_DOWNLOAD_URL: "https://download.blender.org/release/Blender${{ matrix.blender_version%%.* }}/blender-${{ matrix.blender_version }}-linux-x64.tar.xz"
      BLENDER_DIR: "${{ github.workspace }}/blender"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Blender
        id: cache-blender
        uses: actions/cache@v4
        with:
          path: ${{ env.BLENDER_DIR }}
          key: blender-${{ matrix.blender_version }}

      - name: Download Blender if not cached
        if: steps.cache-blender.outputs.cache-hit != 'true'
        run: |
          mkdir -p "${{ env.BLENDER_DIR }}"
          wget -qO- "${{ env.BLENDER_DOWNLOAD_URL }}" | tar -xJ --strip-components=1 -C "${{ env.BLENDER_DIR }}"

      - name: Install pytest in Blender's Python
        run: |
          BLENDER_MAJOR_MINOR=$(echo "${{ env.BLENDER_VERSION }}" | cut -d. -f1,2)
          PYTHON_BIN="${{ env.BLENDER_DIR }}/${BLENDER_MAJOR_MINOR}/python/bin/python3.11m"

          "${{ env.BLENDER_DIR }}/blender" --background --python-expr \
          "import subprocess as sp; \
           python_bin = r'${{ env.BLENDER_DIR }}/' + '${BLENDER_MAJOR_MINOR}' + '/python/bin/python3.11m'; \
           sp.run([python_bin, '-m', 'ensurepip']); \
           sp.run([python_bin, '-m', 'pip', 'install', '--upgrade', 'pip']); \
           sp.run([python_bin, '-m', 'pip', 'install', 'pytest'])"

      - name: Run pytest inside Blender
        env:
          PYTHONPATH: ${{ github.workspace }}/src
          BLENDER_USER_SCRIPTS: ${{ github.workspace }}/src
        run: |
          BLENDER_MAJOR_MINOR=$(echo "${{ env.BLENDER_VERSION }}" | cut -d. -f1,2)
          PYTHON_BIN="${{ env.BLENDER_DIR }}/${BLENDER_MAJOR_MINOR}/python/bin/python3.11m"

          "${{ env.BLENDER_DIR }}/blender" --background --python-expr \
          "import subprocess as sp; \
           python_bin = r'${{ env.BLENDER_DIR }}/' + '${BLENDER_MAJOR_MINOR}' + '/python/bin/python3.11m'; \
           sp.run([python_bin, '-m', 'pytest', '--maxfail=1', '--disable-warnings', '-v', 'src'])"
